def lift(air_density, air_velocity, wing_area, lift_coefficient):
    """Calculates wing lift.

    Calculates the lift generated by the wing based on the following parameters:

    Args:
        air_density {[type]} -- Air density for given altitude
        air_velocity {[type]} -- Free-stream velocity
        wing_area {[type]} -- Wing projected area
        lift_coefficient {[type]} -- Lift coefficient for the wing (CL)

    Returns:

    """

    return 0.5 * air_density * air_velocity^2 * wing_area * lift_coefficient
